name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "gnews2"
database_id = "d9897ed0-c4d4-4417-878a-5e38657903af"
